version: "3.5"
volumes:
  nextcloud:
  apps:
  db:
  config:

services:
  portal:
    image: acatonl/woo-ui-develop
    ports:
    - "8081:80"

  catalog:
    image: ghcr.io/opencatalogi/web-app:dev
    ports:
    - "8082:8080"

  woo:
    image: ghcr.io/conductionnl/woo-website-v2:latest
    ports:
    - "8083:8080"

  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD='!ChangeMe!'
      - MYSQL_PASSWORD='!ChangeMe!'
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    ports:
    - "13306:3306"

  # init-ubuntu:
  #   image: ubuntu
  #   command: sh /home/ubuntu/docker/init-ubuntu.sh
  #   volumes:
  #     - ./docker:/home/ubuntu/docker
  #     - .:/home/ubuntu/app

  nextcloud:
    user: root
    container_name: nextcloud
#    entrypoint: occ app:enable opencatalogi
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html:rw
      - ./custom_apps:/var/www/html/custom_apps
      - .:/var/www/html/custom_apps/opencatalogi
    environment:
      - MYSQL_PASSWORD='!ChangeMe!'
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - TZ=Europe/Amsterdam
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    # depends_on:
    #   init-ubuntu:
    #     condition: service_completed_successfully
