name: ❓ Question
description: Ask a question about OpenCatalogi
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Before asking a question, please check:
        - [Documentation](https://conduction.gitbook.io/opencatalogi-nextcloud/)
        - Existing issues and discussions

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation
        - Configuration
        - Usage
        - Integration
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please provide as much detail as possible
      placeholder: "I would like to know..."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: OpenCatalogi Version
      description: What version of OpenCatalogi are you using?
      placeholder: "e.g. 0.6.43"

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about your question here 