name: Release Workflow

on: [push]

jobs:
  release-management:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # Checkout the correct branch name
          fetch-depth: 0                # Fetch the whole repo history

      # Step 2: Prepare the signing certificate and key
      - name: Prepare Signing Certificate and Key
        run: |
          echo "${{ secrets.NEXTCLOUD_SIGNING_CERT }}" > signing-cert.crt
          echo "${{ secrets.NEXTCLOUD_SIGNING_KEY }}" > signing-key.key

      # Step 3: Install Node.js dependencies using npm
      - name: Install npm dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Specify Node.js version

      # Step 4: Install PHP extensions
      - name: Set up PHP and install extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: zip, gd

      # Step 5: Build the node dependencies
      - run: npm ci

      # Step 6: Build the node dependencies
      - run: npm run build

      # Step 7: Build composer dependencies
      - run: composer i --no-dev

      # Step 8: Copy the files into the package directory, excluding .git and package itself
      - name: Copy the package files into the package
        run: |
          mkdir -p package/opencatalogi
          rsync -av --progress \
            --exclude='package' \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='.vscode' \
            --exclude='docker' \
            --exclude='docs' \
            --exclude='node_modules' \
            --exclude='src' \
            --exclude='test' \
            --exclude='package-lock.json' \
            --exclude='composer.lock' \
            --exclude='composer-setup.php' \
            --exclude='.phpunit.result.cache' \
            --exclude='phpmd.xml' \
            --exclude='signing-key.key' \
            --exclude='package.json' \
            --exclude='composer.json' \
            --exclude='coverage.txt' \
            --exclude='signing-cert.crt' \
            --exclude='docker-compose.yml' \
            --exclude='webpack.config.js' \
            --exclude='.prettierrc' \
            --exclude='psalm.xml' \
            --exclude='phpunit.xml' \
            --exclude='tsconfig.json' \
            --exclude='changelog-ci-config.json' \
            --exclude='jest.config.js' \
            --exclude='.gitattributes' \
            --exclude='.php-cs-fixer.dist.php' \
            --exclude='.gitignore' \
            --exclude='.eslintrc.js' \
            --exclude='stylelint.config.js' \
            --exclude='.babelrc' \
            --exclude='.nvmrc' \
            ./ package/opencatalogi/

      # Step 9: Create the TAR.GZ archive with code in opencatalogi directory
      - name: Create Tarball
        run: |
          cd package && tar -czf ../nexcloud-release.tar.gz opencatalogi    

      # Step 10: Sign the TAR.GZ file with OpenSSL
      - name: Sign the TAR.GZ file with OpenSSL
        run: |
          openssl dgst -sha512 -sign signing-key.key -out nexcloud-release.signature nexcloud-release.tar.gz

      # Step 11: Generate Git version information
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          release-branch: main

      # Step 12: Extract repository description
      - name: Extract repository description
        id: repo-description
        run: |
          description=$(jq -r '.description' <(curl -s https://api.github.com/repos/${{ github.repository }}))
          echo "REPO_DESCRIPTION=$description" >> $GITHUB_ENV

      # Step 13: Run Changelog CI
      - name: Run Changelog CI
        if: github.ref == 'refs/heads/master'
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          release_version: ${{ steps.version.outputs.version }}
          config_file: changelog-ci-config.json

      # Step 14: Output the version
      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.version }}

      # Step 15: Copy the files into the package directory, excluding .git and package itself
      - name: Copy the package files into the package
        run: |
          mkdir -p package/opencatalogi
          rsync -av --progress --exclude='package' --exclude='.git' ./ package/opencatalogi/

      # Step 16: Create the ZIP archive with code in opencatalogi directory
      - name: Create ZIP
        run: |
          cd package && zip -r ../opencatalogi-build.zip opencatalogi

      # Step 17: Create the TAR.GZ archive with code in opencatalogi directory
      - name: Create Tarball
        run: |
          cd package && tar -czf ../opencatalogi-build.tar.gz opencatalogi    

      # Step 18: Create a new release on GitHub
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: |
            LICENSE.md
            nexcloud-release.tar.gz
            nexcloud-release.signiture
            opencatalogi-build.zip
            opencatalogi-build.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version.outputs.version }}
