name: Release Workflow

on: [push]

jobs:
  release-managment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      #Based on https://github.com/marketplace/actions/git-version
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          release-branch: main

      - name: Extract repository description
        id: repo-description
        run: |
          description=$(jq -r '.description' <(curl -s https://api.github.com/repos/${{ github.repository }}))
          echo "REPO_DESCRIPTION=$description" >> $GITHUB_ENV

      #https://github.com/saadmk11/changelog-ci
      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          release_version: ${{ steps.version.outputs.version }}
          config_file: changelog-ci-config.json

      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.version }}

      #https://github.com/marketplace/actions/zip-release
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git* *.vscode* .coverage-frontend* .docker* .tests* .specs.ts* .mocks.ts* .tests* .editorconfig .eslintrc.js .phpmd.xml .phpunit.xml .psalm.xml .eslintrc.js stylelint.config.js webpack.config.js' 

      #https://github.com/marvinpinto/action-automatic-releases
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.version.outputs.version }}
          prerelease: false
          title: "Release ${{ steps.version.outputs.version }}"
          files: |
            LICENSE.md
            release.zip